### ISSUE TITLE
images update problem

### ISSUE THREAD

**Issue by tumblingG** [yuanchuan/node-watch#127]
![image](https://github.com/yuanchuan/node-watch/assets/29335868/73d3138b-9a55-4d0d-959b-3fb864a64c0f)
![image](https://github.com/yuanchuan/node-watch/assets/29335868/c205bd65-ca0c-4f54-ad8f-0995498158db)

I monitor my engineering projects. When I opened the images folder of my project from windows D, the update automatically triggered, but I didn't actually change the images. And the js files sometimes update automatically even though I haven't changed anything, why?

**Comment by tumblingG** [comment]
![image](https://github.com/yuanchuan/node-watch/assets/29335868/e24e8629-6c2c-4f2f-8582-8b6813d9a382)

When I use the local proxy to access the local file, the js file will also trigger the update. Is the browser changing the file?

**Comment by yuanchuan** [comment]
There is nothing to do with `node-watch`. Replacing `watch` with `fs.watch` would be the same. 

When you open a directory your OS system may update some meta data of that directory. Since you're watching the whole directory recursively that callback will be triggered anyway. And sometimes the editors will save files silently even if the `save` button isn't being touched.

**Comment by yuanchuan** [comment]
One way to avoid the blindly calling is to detect the file types which you're going to handle. For example, inside the callback function:

```js
watch('somehere', {recursive: true}, (evt, pathname) => {
  if (/\.png$/.test(pathname)) {
     // do something
  }
});
```

You can also increase the `delay` so that the `setTimeout` thing in your code would be unnecessary.

```js
watch('somewhere', { recursive: true, delay: 1000 }, (evt, pathname) => {

});
```


```
